// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Entity.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary Key. Auto-incremented.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("Timestamp when the car was created.");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("integer")
                        .HasComment("Year the car was manufactured.");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("integer")
                        .HasComment("FK referencing the Manufacturer of this car.");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Car model name (e.g., Corolla, X5).");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Price of the car.");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of cars available in stock.");

                    b.HasKey("Id")
                        .HasName("cars_pkey");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Cars", null, t =>
                        {
                            t.HasComment("Stores information about cars.");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4740),
                            ManufactureYear = 2094,
                            ManufacturerId = 3,
                            Model = "Ford-Model-0",
                            Price = 28410.92m,
                            Stock = 69
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4792),
                            ManufactureYear = 2081,
                            ManufacturerId = 8,
                            Model = "Maruti Suzuki-Model-1",
                            Price = 47236.16m,
                            Stock = 649
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4797),
                            ManufactureYear = 1908,
                            ManufacturerId = 5,
                            Model = "Hyundai-Model-2",
                            Price = 22300.07m,
                            Stock = 149
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4802),
                            ManufactureYear = 2087,
                            ManufacturerId = 8,
                            Model = "Maruti Suzuki-Model-3",
                            Price = 17010.07m,
                            Stock = 325
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4805),
                            ManufactureYear = 1907,
                            ManufacturerId = 4,
                            Model = "Honda-Model-4",
                            Price = 53545.48m,
                            Stock = 786
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4810),
                            ManufactureYear = 1975,
                            ManufacturerId = 5,
                            Model = "Hyundai-Model-5",
                            Price = 17747.84m,
                            Stock = 524
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4813),
                            ManufactureYear = 2075,
                            ManufacturerId = 8,
                            Model = "Maruti Suzuki-Model-6",
                            Price = 59348.23m,
                            Stock = 557
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4816),
                            ManufactureYear = 2072,
                            ManufacturerId = 3,
                            Model = "Ford-Model-7",
                            Price = 11924.95m,
                            Stock = 327
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4819),
                            ManufactureYear = 2090,
                            ManufacturerId = 1,
                            Model = "Toyota-Model-8",
                            Price = 11841.12m,
                            Stock = 426
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4824),
                            ManufactureYear = 1990,
                            ManufacturerId = 8,
                            Model = "Maruti Suzuki-Model-9",
                            Price = 36001.98m,
                            Stock = 154
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4827),
                            ManufactureYear = 1947,
                            ManufacturerId = 5,
                            Model = "Hyundai-Model-10",
                            Price = 58930.18m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4833),
                            ManufactureYear = 1958,
                            ManufacturerId = 9,
                            Model = "AvtoVAZ (Lada)-Model-11",
                            Price = 24385.79m,
                            Stock = 243
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4837),
                            ManufactureYear = 1964,
                            ManufacturerId = 8,
                            Model = "Maruti Suzuki-Model-12",
                            Price = 49049.32m,
                            Stock = 565
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4840),
                            ManufactureYear = 2087,
                            ManufacturerId = 4,
                            Model = "Honda-Model-13",
                            Price = 36592.93m,
                            Stock = 618
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4842),
                            ManufactureYear = 1983,
                            ManufacturerId = 10,
                            Model = "GAZ-Model-14",
                            Price = 59831.21m,
                            Stock = 699
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4845),
                            ManufactureYear = 2091,
                            ManufacturerId = 8,
                            Model = "Maruti Suzuki-Model-15",
                            Price = 21294.76m,
                            Stock = 702
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4848),
                            ManufactureYear = 2068,
                            ManufacturerId = 3,
                            Model = "Ford-Model-16",
                            Price = 50561.68m,
                            Stock = 340
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4853),
                            ManufactureYear = 1928,
                            ManufacturerId = 10,
                            Model = "GAZ-Model-17",
                            Price = 54131.31m,
                            Stock = 416
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4856),
                            ManufactureYear = 2094,
                            ManufacturerId = 5,
                            Model = "Hyundai-Model-18",
                            Price = 11074.29m,
                            Stock = 235
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4858),
                            ManufactureYear = 2079,
                            ManufacturerId = 6,
                            Model = "Tata Motors-Model-19",
                            Price = 59419.44m,
                            Stock = 485
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4862),
                            ManufactureYear = 1962,
                            ManufacturerId = 3,
                            Model = "Ford-Model-20",
                            Price = 58230.88m,
                            Stock = 905
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4864),
                            ManufactureYear = 1915,
                            ManufacturerId = 5,
                            Model = "Hyundai-Model-21",
                            Price = 21618.40m,
                            Stock = 279
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4867),
                            ManufactureYear = 1910,
                            ManufacturerId = 7,
                            Model = "Mahindra-Model-22",
                            Price = 39287.95m,
                            Stock = 338
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4870),
                            ManufactureYear = 2044,
                            ManufacturerId = 5,
                            Model = "Hyundai-Model-23",
                            Price = 13401.25m,
                            Stock = 463
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4873),
                            ManufactureYear = 1920,
                            ManufacturerId = 7,
                            Model = "Mahindra-Model-24",
                            Price = 57433.17m,
                            Stock = 556
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4875),
                            ManufactureYear = 1957,
                            ManufacturerId = 5,
                            Model = "Hyundai-Model-25",
                            Price = 33066.12m,
                            Stock = 601
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4878),
                            ManufactureYear = 2049,
                            ManufacturerId = 8,
                            Model = "Maruti Suzuki-Model-26",
                            Price = 55806.45m,
                            Stock = 750
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4880),
                            ManufactureYear = 2005,
                            ManufacturerId = 7,
                            Model = "Mahindra-Model-27",
                            Price = 50777.99m,
                            Stock = 116
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4883),
                            ManufactureYear = 1933,
                            ManufacturerId = 5,
                            Model = "Hyundai-Model-28",
                            Price = 15303.64m,
                            Stock = 590
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4885),
                            ManufactureYear = 1984,
                            ManufacturerId = 1,
                            Model = "Toyota-Model-29",
                            Price = 55350.97m,
                            Stock = 982
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4888),
                            ManufactureYear = 2022,
                            ManufacturerId = 10,
                            Model = "GAZ-Model-30",
                            Price = 11693.56m,
                            Stock = 519
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4891),
                            ManufactureYear = 2059,
                            ManufacturerId = 8,
                            Model = "Maruti Suzuki-Model-31",
                            Price = 37935.43m,
                            Stock = 545
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4894),
                            ManufactureYear = 1968,
                            ManufacturerId = 6,
                            Model = "Tata Motors-Model-32",
                            Price = 38912.37m,
                            Stock = 322
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4940),
                            ManufactureYear = 2050,
                            ManufacturerId = 5,
                            Model = "Hyundai-Model-33",
                            Price = 33230.07m,
                            Stock = 679
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4944),
                            ManufactureYear = 1928,
                            ManufacturerId = 3,
                            Model = "Ford-Model-34",
                            Price = 19078.32m,
                            Stock = 240
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4946),
                            ManufactureYear = 2037,
                            ManufacturerId = 10,
                            Model = "GAZ-Model-35",
                            Price = 57581.07m,
                            Stock = 855
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4949),
                            ManufactureYear = 2098,
                            ManufacturerId = 2,
                            Model = "BMW-Model-36",
                            Price = 53591.82m,
                            Stock = 183
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4952),
                            ManufactureYear = 1984,
                            ManufacturerId = 7,
                            Model = "Mahindra-Model-37",
                            Price = 13029.82m,
                            Stock = 41
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4955),
                            ManufactureYear = 1945,
                            ManufacturerId = 4,
                            Model = "Honda-Model-38",
                            Price = 45782.15m,
                            Stock = 898
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4957),
                            ManufactureYear = 2069,
                            ManufacturerId = 6,
                            Model = "Tata Motors-Model-39",
                            Price = 19604.71m,
                            Stock = 531
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4960),
                            ManufactureYear = 1929,
                            ManufacturerId = 1,
                            Model = "Toyota-Model-40",
                            Price = 40271.30m,
                            Stock = 770
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4963),
                            ManufactureYear = 2049,
                            ManufacturerId = 2,
                            Model = "BMW-Model-41",
                            Price = 14863.72m,
                            Stock = 647
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4965),
                            ManufactureYear = 2059,
                            ManufacturerId = 10,
                            Model = "GAZ-Model-42",
                            Price = 46765.88m,
                            Stock = 916
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4968),
                            ManufactureYear = 1995,
                            ManufacturerId = 4,
                            Model = "Honda-Model-43",
                            Price = 27131.97m,
                            Stock = 361
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4970),
                            ManufactureYear = 2041,
                            ManufacturerId = 5,
                            Model = "Hyundai-Model-44",
                            Price = 19490.16m,
                            Stock = 599
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4974),
                            ManufactureYear = 1951,
                            ManufacturerId = 3,
                            Model = "Ford-Model-45",
                            Price = 44810.73m,
                            Stock = 503
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4976),
                            ManufactureYear = 2042,
                            ManufacturerId = 5,
                            Model = "Hyundai-Model-46",
                            Price = 22661.54m,
                            Stock = 421
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4978),
                            ManufactureYear = 1920,
                            ManufacturerId = 8,
                            Model = "Maruti Suzuki-Model-47",
                            Price = 32614.16m,
                            Stock = 396
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4981),
                            ManufactureYear = 1931,
                            ManufacturerId = 4,
                            Model = "Honda-Model-48",
                            Price = 20271.05m,
                            Stock = 785
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4985),
                            ManufactureYear = 1930,
                            ManufacturerId = 4,
                            Model = "Honda-Model-49",
                            Price = 48357.55m,
                            Stock = 259
                        });
                });

            modelBuilder.Entity("Data.Entity.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary Key. Auto-incremented.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Country where the manufacturer is based.");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("Timestamp when the manufacturer was created.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Name of the manufacturer (e.g., Toyota, BMW).");

                    b.HasKey("Id")
                        .HasName("manufacturers_pkey");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Manufacturers", null, t =>
                        {
                            t.HasComment("Stores car manufacturer information.");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Japan",
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4600),
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Germany",
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4614),
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 3,
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4616),
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Japan",
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4618),
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 5,
                            Country = "South Korea",
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4620),
                            Name = "Hyundai"
                        },
                        new
                        {
                            Id = 6,
                            Country = "India",
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4621),
                            Name = "Tata Motors"
                        },
                        new
                        {
                            Id = 7,
                            Country = "India",
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4622),
                            Name = "Mahindra"
                        },
                        new
                        {
                            Id = 8,
                            Country = "India",
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4624),
                            Name = "Maruti Suzuki"
                        },
                        new
                        {
                            Id = 9,
                            Country = "Russia",
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4625),
                            Name = "AvtoVAZ (Lada)"
                        },
                        new
                        {
                            Id = 10,
                            Country = "Russia",
                            CreatedAt = new DateTime(2025, 9, 2, 17, 20, 36, 299, DateTimeKind.Local).AddTicks(4627),
                            Name = "GAZ"
                        });
                });

            modelBuilder.Entity("Data.Entity.Car", b =>
                {
                    b.HasOne("Data.Entity.Manufacturer", "Manufacturer")
                        .WithMany("Cars")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("cars_manufacturerid_fkey");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("Data.Entity.Manufacturer", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
